[behave]
# -------------------------------------------------
# Test discovery
# -------------------------------------------------
paths = features
show_skipped = false
show_timings = true

# -------------------------------------------------
# Allure reporting
# -------------------------------------------------
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results

# -------------------------------------------------
# Logging & output
# -------------------------------------------------
stdout_capture = false
stderr_capture = false
log_capture = false
logging_level = INFO

# -------------------------------------------------
# Execution control
# -------------------------------------------------
stop = false
dry_run = false

# -------------------------------------------------
# User-defined runtime data (API specific)
# -------------------------------------------------
userdata =
    env=qa
    base_url=https://ms-api-gateway-qa.azurewebsites.net
    offers_endpoint=/offers/v1/offers
    countryCode=GB
    contentType=application/json