name: Behave ESTAF Automation

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave Tests
        run: behave
      - name: Generate Coverage Report
        run: |
          coverage report -m

      #- name: Run report script using absolute path
      #  run: python ${{ github.workspace }}/generate_report.py

      - name: Run report generation script
        run: python generate_report.py


      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4 # Use version 4 (or later) as recommended
        with:
          name: Execution-Status-Report # The name of your artifact
          path: reports/Execution-Status-Report.xlsx